### ISSUE TITLE
Example on https://newsapi.org/docs/client-libraries/node-js throws an error

### ISSUE THREAD

**Issue by mayeaux** [bzarras/newsapi#17]
The example on the newsapi site for this library is broken. It is listed as: 

```
newsapi.v2.topHeadlines({
  sources: 'bbc-news,the-verge',
  q: 'bitcoin',
  category: 'business',
  language: 'en',
  country: 'us'
}).then(response => {
  console.log(response);
  /*
    {
      status: "ok",
      articles: [...]
    }
  */
});
```

returns 
`NewsAPIError: parametersIncompatible: You cannot mix the sources parameter with the country or category parameters.`

Just a heads up, may want to have that fixed

**Comment by SEAN0905** [comment]
I'm also having the same problem with python
