### ISSUE TITLE
core-js compilation error

### ISSUE THREAD

**Issue by FeynmanTesla** [bzarras/newsapi#18]
The following error frequently occurs on npm compilations (runnning npm start with a React app):

./node_modules/newsapi/dist/index.js
Module not found: Can't resolve 'core-js/modules/es6.array.index-of' in '/my-app/node_modules/newsapi/dist'

**Comment by dinhkhanh** [comment]
Have you fixed it? I'm facing the same issue.

**Comment by Mobiletainment** [comment]
I had to **downgrade `core-js`** and ended up using version 2.6.11 instead of 3.x.

**Comment by bzarras** [comment]
This should be fixed with the latest release. Going to close this out.
