### ISSUE TITLE
Unhandled promise rejections

### ISSUE THREAD

**Issue by rohanshukla9** [bzarras/newsapi#19]
So I've made around 10 requests to this api using a developer account and I already got this error and asking me to upgrade my plan to make more requests lol

> UnhandledPromiseRejectionWarning: NewsAPIError: parameterInvalid: You are trying to request results too far in the past. Your plan permits you to request articles as far back as 2019-07-07, but you have requested 2019-07-01. To extend this please upgrade to a paid plan.

**Comment by monooso** [comment]
@rohanshukla9 The issue isn't the number of requests, it's the specified date range. The developer plan is limited to articles up to a month old.
