### ISSUE TITLE
Filtering by keyword

### ISSUE THREAD

**Issue by dleitner100** [bzarras/newsapi#3]
I'm wondering if it is possible to filter news articles by a keyword. For example to filter by "climate change".
As far as I know you can only filter by the source of the press.

**Comment by bzarras** [comment]
Hi dleitner100,

Filtering by keyword was added as a feature in V2 of NewsAPI: https://newsapi.org/docs/v2-migration#keyword-search

Support for this feature from this module will be added soon. I will keep you posted

**Comment by bzarras** [comment]
Keyword filtering is now available via the V2 API. I'm going to close this issue.
