### ISSUE TITLE
Problem with CORS policy, when making a request to https://newsapi.org

### ISSUE THREAD

**Issue by onurusluca** [bzarras/newsapi#32]
When testing api from localhost, it gives me this error. I tried everything. To duplicate you can just try to call any api any way you want and it will give this error..

Testing on [Node.js ](https://newsapi.org/docs/client-libraries/node-js)

Access to fetch at 'https://newsapi.org/v2/everything?q=bitcoin&sources=bbc-news%2Cthe-verge&domains=bbc.co.uk%2C%20techcrunch.com&language=en&sortBy=relevancy&page=2' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by Abban-Fahim** [comment]
Yep same here :(

**Comment by jmarrr** [comment]
I still get this issue, even with the suggested fix from the readme

**Comment by onurusluca** [comment]
Closing due to no answer.
