### ISSUE TITLE
Doesn't minify with webpack in a create-react-app project.

### ISSUE THREAD

**Issue by jpramassini** [bzarras/newsapi#9]
When attempting to output a production build, the package is unable to minify. I got around this by manually creating an ES5 version, but I wanted to put it out there for anybody else that may run into the issue.

**Comment by Imperator145** [comment]
Same problem here

**Comment by bzarras** [comment]
Thanks for reporting this. Sounds like an ES5 distribution of the package is needed. Will get this resolved soon

**Comment by bzarras** [comment]
@Imperator145 Support for ES5 has been added. Please let me know if this resolves your issue
